#!/bin/sh

send_notification() {
  brightness=$(brillo -G)
  dunstify -a "changebrightness" -r 9993 -h int:value:"$brightness" "Brightness: ${brightness}%" -t 2000
}

case $1 in
  up) 
    brillo -q -A $2
    send_notification
    ;;
  down)
    brillo -q -U $2
    send_notification
    ;;
  *) exit ;;
esac
