#!/bin/sh

sync && case $(printf "Shutdown\nReboot\nLogout" | dmenu -l 3 -p "Session end command") in
  Shutdown) shutdown -h now ;;
  Reboot) reboot ;;
  Logout) pkill -KILL -u $USER ;;
  *) ;;
esac
