#!/bin/sh

# paru cache location
AUR_CACHE_DIR=$HOME/.cache/paru/clone

# Cache dirs
AUR_CACHE_REMOVED="$(find "$AUR_CACHE_DIR" -maxdepth 1 -type d | awk '{print "-c " $1}' | tail -n +2)"
# Uninstalled aur package cache
AUR_REMOVED=$(/usr/bin/paccache -ruvk0 $AUR_CACHE_REMOVED | sed '/\.cache/!d' | cut -d \' -f 2 | rev | cut -d / -f2- | rev)
[-z "$AUR_REMOVED"] || rm -rf $AUR_REMOVED

AUR_CACHE="$(find "$AUR_CACHE_DIR" -maxdepth 1 -type d | awk '{ print "-c " $1 }' | tail -n +2)"
/usr/bin/paccache -qruk1
/usr/bin/paccache -qrk2 -c /var/cache/pacman/pkg $AUR_CACHE
